# Generated by Django 6.0.6 on 2026-07-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_current_amount_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images/'),
        ),
    ]
